const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'..');
const server=http.createServer(async(req,res)=>{try{const name=new URL(req.url,'http://local').pathname.slice(1)||'index.html';const p=path.resolve(root,name);if(!p.startsWith(root+path.sep)){res.writeHead(403);return res.end();}let data;if(fs.existsSync(p))data=fs.readFileSync(p);else{const r=await fetch('https://raw.githubusercontent.com/boundary-x/micro-bit_bt_gamepad/main/'+name);res.statusCode=r.status;data=Buffer.from(await r.arrayBuffer());}res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':'application/octet-stream');res.end(data);}catch(e){res.writeHead(502);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({serviceWorkers:'block'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>document.getElementById('settings-controller-up').value==='U');
for(const [width,height] of [[320,740],[390,844],[430,932],[768,1024],[844,390],[1280,900]]){await page.setViewportSize({width,height});await page.locator('#button-help').click();await page.locator('#start-tour').click();for(let i=0;i<6;i++){await page.waitForTimeout(50);const b=await page.locator('#tour-panel').boundingBox();assert(b.x>=0&&b.y>=0&&b.x+b.width<=width+1&&b.y+b.height<=height+1,JSON.stringify({width,i,b}));const spot=await page.locator('#tour-spot').boundingBox();assert(spot.width>0&&spot.height>0,'visible highlight');assert(!(spot.x<b.x+b.width&&spot.x+spot.width>b.x&&spot.y<b.y+b.height&&spot.y+spot.height>b.y),'highlight overlaps panel');await page.keyboard.press('f');assert.equal(await page.locator('#commands-log').textContent(),'');await page.locator('#tour-next').click();}assert(await page.locator('#game-support').evaluate(e=>e.open));await page.keyboard.press('Escape');console.log('PASS guide '+width);}
await page.locator('#button-settings').click();await page.locator('#settings-controller-a').fill('forward');await page.locator('#settings-controller-a').press('Tab');assert.equal(await page.locator('#commands-log').textContent(),'');await page.locator('#settings-close').click();await page.waitForTimeout(600);await page.locator('#button-help').click();await page.locator('#support-mapping > summary').click();assert((await page.locator('#mapping-body').textContent()).includes('forward'));await page.keyboard.press('f');assert.equal(await page.locator('#commands-log').textContent(),'');await page.keyboard.press('Escape');await page.keyboard.press('f');assert((await page.locator('#commands-log').textContent()).includes('Pressed: a'));
await page.locator('#full-screen-icon').click();await page.waitForFunction(()=>!!document.fullscreenElement);await page.locator('#fullscreen-help').click();assert(await page.locator('#game-support').evaluate(e=>e.open));await page.locator('#start-tour').click();await page.waitForFunction(()=>!document.fullscreenElement);await page.keyboard.press('Escape');await page.locator('#support-close').click();assert.deepEqual(errors,[]);console.log('PASS mapping, keyboard guards, restored controls and fullscreen');
await page.locator('#button-help').click();await page.screenshot({path:path.join(root,'support-preview.png')});
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
